[build]
  command = "ng build --configuration production"
  publish = "dist/front-end/browser"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

